### PR TITLE
Configurable Entry parameters

### PR DESCRIPTION
**Pull request by Jamie4224**
I made some changes to the Entry class, which will allow you to feed configuration parameters to the constructor. This allows people to use multiple Zoom API keys if necessary, or change the baseurl on demand.

I also added some documentation in the readme file.

Hope this is useful :)

### CODE REVIEW

**Comment by colinhall17** [comment]
Hi @Jamie4224 

Thanks for the PR

The package needs to be compatible from PHP7.3, can you make the necessary changes to make it compatible with 7.3?

**Comment by Jamie4224** [comment]
Hello @colinhall17 

Yes, I will do that. Just 2 minutes ago I got a deprecated error, will fix this.

**Comment by Jamie4224** [comment]
@colinhall17 I hope this latest commit is completely compatible. I also tested it in my Laravel environment and it works just like it did.

**Comment by colinhall17** [comment]
@Jamie4224 

Thanks for the amendment, worked fine in my environment too so merging in.  In the next major version I will make it PHP 8 minimum and make the changes you first supplied.

Thanks for your contribution.

**Pull request merged**
